<?php

$data = file_get_contents("php://input");
$data = json_decode( $data, true );

$name = $data['name'];	
$email = $data['email'];
$bug = $data['subject'];
$subject = $data['subject'];
$problem = $data['problem'];
$today = date("F j, Y - g:i a");

$to = 'pripley@siue.edu, jmccord@siue.edu, jacohen@siue.edu';
$subject = 'Bug in HIVE: ' . $subject;
$message = "New bug report from Hive!\n\nName:\t" . $name . "\nEmail:\t" . $email . "\nDate:\t" . $today . "\n\nBug:\t" . $bug . "\n\nProblem Description:\n". $problem . "\n\n\nTo reply to the user, hit reply (use Reply All so we're all informed) and send your response.\nEmail generated by HIVE.\n" .
	"                 . '   ' .            __    \n" . 
	"       .         .       .           (__\_  \n" .
	"         .         .   .         . -{{_(|8)<\n" .
	"            '   .  . ' .   .   '     (__/   \n";
$headers = 'From: HIVE <hive@isg.siue.edu>' . "\r\n" .
	'Reply-To: ' . $email . "\r\n" .
	'X-Mailer: PHP/' . phpversion();

mail($to, $subject, $message, $headers);
?>